### ISSUE TITLE
Add babel runtime to prod version dependencies

### ISSUE THREAD

**Issue by zobione** [NickTomlin/mailchimp-lite#2]
I have an issue when installing my app in production. Can you add babel-runtime as a dependency ?

Error: Cannot find module 'babel-runtime/helpers/get'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/data/web/vhosts/default/node_modules/mailchimp-lite/dist/index.js:3:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/data/web/vhosts/default/app/routes.js:33:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by NickTomlin** [comment]
Thanks for the heads up! This has been fixed and released. Let me know if it's still not working 😄

**Comment by zobione** [comment]
Thanks ! working fine!
